-- Legal frameworks and causation doctrines for toxic-tort litigation
-- Complements regulatory classifications from 008_reference_regulatory_seed.sql
-- Lawyer-education reference layer

INSERT INTO reference_terms (slug, name, category, short_definition, deep_explanation_md, lawyer_angle, daubert_relevance, citations, aliases, related_terms)
VALUES

('daubert-standard', 'Daubert Standard', 'legal_standard',
'Federal Rule of Evidence 702 gatekeeping test establishing admissibility of expert testimony based on testability, peer review, error rate, standards, and general acceptance.',
'The Daubert standard emerged from Daubert v. Merrell Dow Pharmaceuticals, Inc., 509 U.S. 579 (1993), which fundamentally reshaped federal expert testimony law. Rather than applying the Frye "general acceptance" test, the Supreme Court held that FRE 702 requires courts to assess the reliability of the underlying methodology itself. The five Daubert factors—(1) testability/falsifiability; (2) peer review and publication; (3) known or potential error rate; (4) controlling standards and protocols; (5) general acceptance—are not a rigid checklist but a flexible inquiry tailored to the expert''s field.

In toxic-tort litigation, Daubert gatekeeping directly impacts epidemiological testimony, dose-response modeling, biomarker interpretation, and mechanistic causation evidence. The Kumho Tire Co. v. Carmichael, 526 U.S. 137 (1999) trilogy extension clarified that the test applies to all expert testimony, not just science-based opinions. General Electric Co. v. Joiner, 522 U.S. 136 (1997), established that appellate courts review gatekeeping decisions for abuse of discretion, giving trial courts substantial deference.

Post-2000 amendments to FRE 702 codified Daubert factors into statutory language: "scientific . . . knowledge will help the trier of fact . . . [based on] sufficient facts or data . . . [using] reliable principles and methods . . . [properly] applied to the facts." This shift from judge-as-scientist to judge-as-gatekeeper does not immunize sloppy science; courts regularly exclude testimony failing the reliability prong.

State courts have adopted Daubert (NY, CA, TX, IL, PA, NJ, MA, WA, MI) or retained Frye (a shrinking minority), but federal litigation—the bulk of mass-tort discovery—applies Daubert uniformly. Recent appellate scrutiny has tightened: courts are skeptical of extrapolation from high-dose animal studies to low-dose human exposure without mechanistic bridge.',
'Every toxicology expert disclosure in federal court invites a Daubert challenge. Opposing counsel will dissect methodology, probe error rates, demand published protocols, and argue the application to your plaintiff is speculative or extrapolated beyond peer-reviewed bounds. Anticipate attacks on dose-response assumptions, biomarker specificity, and "gulf between study conditions and actual exposure." The bar is admissibility, not credibility; pass Daubert and the jury decides weight. Failure is case-dispositive.',
'Daubert challenges succeed most often on prong (1) testability—specifically, whether a dose-response or biomarker threshold was pre-specified or reverse-engineered post-hoc—and prong (4) standards, when the expert''s protocol deviates from published epidemiological guidance. Recent federal practice shows heightened skepticism of expert extrapolation: courts demand statistically adequate sample sizes and peer-reviewed support for the leap from group-level (general causation) to individual (specific causation) claims.',
'{"cases": [{"citation": "Daubert v. Merrell Dow Pharmaceuticals, Inc., 509 U.S. 579 (1993)", "ratio": "Reliability inquiry replaces Frye general-acceptance test; five-factor approach"}, {"citation": "Kumho Tire Co. v. Carmichael, 526 U.S. 137 (1999)", "ratio": "Daubert applies beyond pure science to specialized knowledge and engineering"}, {"citation": "General Electric Co. v. Joiner, 522 U.S. 136 (1997)", "ratio": "Abuse-of-discretion standard for appellate review; substantial deference to trial court"}, {"citation": "Crane Co. v. DeLisle, 258 So. 3d 1219 (Fla. 2018)", "ratio": "Reversed Daubert exclusion; industrial hygienist opinion on every-exposure causation admissible under Florida law"}, {"citation": "In re Lipitor (Atorvastatin Calcium) Products Liability Litigation, 892 F.3d 624 (4th Cir. 2018)", "ratio": "Excluded general-causation testimony as speculative; error rate and dose-response foundation required"}]}',
ARRAY['FRE 702 gatekeeping', 'reliability standard', 'expert admissibility threshold'],
ARRAY['frye-standard', 'fre-702', 'general-causation', 'specific-causation']
),

('frye-standard', 'Frye Standard', 'legal_standard',
'1923 federal test for expert testimony based on general acceptance of the methodology in the relevant scientific community. Still controlling in minority of state courts.',
'Frye v. United States, 293 F. 1013 (D.C. Cir. 1923), established a single gatekeeping question: Is the proffered scientific principle or discovery "sufficiently established to have gained general acceptance in the particular field in which it belongs?" This general-acceptance test preceded Daubert by 70 years and remains the controlling standard in a handful of state jurisdictions (New York, California pre-1995, Illinois, New Jersey, Pennsylvania, Washington state).

Under Frye, the focus is narrow: peer-reviewed acceptance within the relevant scientific field. There is no explicit multi-factor balancing; the court asks whether the methodology has crossed a threshold of reliability through consensus. Frye is more conservative in some respects (requiring genuine consensus) and more rigid in others (no flexibility for novel but reliable methods that lack time-tested acceptance).

In toxic-tort practice, Frye has become jurisdictionally important. New York state courts still apply Frye to toxicology testimony; recent cases denying admission of biomarker evidence for specific causation hinge on failure to show "general acceptance" of the biomarker as predictive in that particular disease state. Pennsylvania and Washington courts similarly scrutinize epidemiological methodology and mechanistic testimony under the Frye lens.

The key strategic distinction: under Frye, you must show the scientific community has vetted and accepted the method, not merely that the method *could* work or that one expert has found it reliable. Absence of published commentary or replication weakens the Frye case. Conversely, if your method is published in high-impact journals and cited by dozens of peers, Frye becomes easier to satisfy.

Frye does not override itself for "new" science; courts in Frye jurisdictions have excluded novel molecular biomarkers as not yet generally accepted, even when mechanistically sound and preliminarily validated. The standard rewards methodological conservatism.',
'If your trial is in a Frye jurisdiction, your toxicology expert must affirmatively demonstrate that peer-reviewed literature and consensus among practicing toxicologists accept the methodology as sufficiently reliable. A single published paper is insufficient; opposing counsel will argue it''s an outlier. You need multiple independent replication, citation in textbooks, and ideally testimony from peers that the field considers it settled science. Frye is harder to clear for novel-but-sound methods; Daubert is harder to clear for sloppy methodology applied to edge cases.',
'Frye challenges rarely cite specific error-rate or standard-protocols data; instead they attack the expert''s assertion of "general acceptance." Discovery demands lists of scientific societies, textbooks, and corroborating publications. If your field has divided opinion, Frye claims fail. Recent Frye-jurisdiction cases show courts deferring to professional societies (e.g., ACGIH for occupational exposure limits) as proxies for "general acceptance."',
'{"cases": [{"citation": "Frye v. United States, 293 F. 1013 (D.C. Cir. 1923)", "ratio": "General-acceptance test: sufficiently established to have gained general acceptance in the particular field"}, {"citation": "People v. Leahy, 8 Cal.4th 587 (1994)", "ratio": "California adopted Daubert, rejecting Frye"}, {"citation": "State v. Ford, 158 N.J. 599 (1999)", "ratio": "New Jersey continues to apply Frye standard to scientific evidence"}]}',
ARRAY['general-acceptance test', 'pre-Daubert standard'],
ARRAY['daubert-standard', 'fre-702', 'general-causation', 'specific-causation']
),

('fre-702', 'Federal Rule of Evidence 702', 'legal_standard',
'Post-2000 statutory codification of Daubert factors: expert testimony admissible if scientific knowledge, reliable methodology/principles, and reliable application assist the trier of fact.',
'Federal Rule of Evidence 702, amended in 2000 to incorporate Daubert principles and again in 2023 to emphasize gatekeeping rigor, reads: "A witness who is qualified as an expert by knowledge, skill, experience, training, or education may testify in the form of an opinion or otherwise if: (a) the expert''s scientific, technical, or other specialized knowledge will help the trier of fact to understand the evidence or to determine a fact in issue; (b) the testimony is based on sufficient facts or data; (c) the testimony is the product of reliable principles and methods; and (d) the expert has reliably applied the principles and methods to the facts of the case."

This statutory language operationalizes Daubert''s multi-factor inquiry. The four prongs are conjunctive: all must be satisfied for admissibility. Prong (c)—reliability of principles and methods—is the gatekeeper inquiry; prong (d)—reliable application—is where courts scrutinize whether the expert''s reasoning chain is valid and not speculative.

In toxic-tort litigation, FRE 702 is the federal baseline. Courts invoke it when excluding exposure-reconstruction testimony (insufficient data to support dose estimates), dose-response extrapolation (unexplained leap from animal studies to human low-dose risk), and differential-diagnosis opinions (failure to rule out alternative etiologies). The 2023 amendment heightened judicial gatekeeping: advisory committee notes emphasize that "preliminary questions" under FRE 104(a) do not shield unreliable opinions; the judge must affirmatively find reliability.

Distinguish admissibility (FRE 702 pass) from weight and credibility (jury determination). An expert can pass FRE 702 and still be impeached, contradicted, or given little weight by the jury; non-admission is the far more severe consequence. Federal courts increasingly apply FRE 702 strictly in mass-tort discovery, particularly when plaintiffs'' experts rely on extrapolation, assumptions about bioavailability, or population-level data applied to individual causation without mechanistic bridge.',
'Your disclosure must anticipate FRE 702 scrutiny of all four prongs: Is the knowledge scientific or speculative? (prong a); does the expert rely on sufficient facts or guesswork? (prong b); are the principles and methods published and tested? (prong c); has the expert actually applied them logically to *this plaintiff*, or merely asserted conclusions? (prong d). Defense motions to exclude will cherry-pick ambiguities in prongs (b) and (d). Pre-emptive narrative and explicit methodology in the report defang such attacks.',
'Prong (c) "reliable principles and methods" fails most often when the expert relies on a single published paper, animal studies without mechanistic bridge to humans, or proprietary algorithms lacking peer-review. Prong (d) "reliable application" fails when the expert''s dose-response model uses inputs not supported by cited literature or when differential diagnosis omits plausible competing etiologies. Recent circuit decisions exclude testimony under prongs (c)/(d) without detailed error-rate discussion, implying that general implausibility suffices to filter unreliable application.',
'{"rules": [{"citation": "Federal Rule of Evidence 702 (2000 Amendment & 2023 Amendment)", "text": "Four-prong test: scientific knowledge, sufficient facts/data, reliable principles/methods, reliable application. 2023 Amendment advisory notes emphasize gatekeeping rigor."}]}',
ARRAY['FRE 702 gatekeeping', 'expert admissibility', 'Daubert statutory codification'],
ARRAY['daubert-standard', 'frye-standard', 'general-causation', 'specific-causation']
),

('general-causation', 'General Causation', 'concept',
'Threshold causation question: Can substance X cause disease Y in humans at any dose? Established by epidemiology, animal toxicology, and regulatory agency classifications.',
'General causation is the foundational liability hurdle in toxic-tort litigation. It asks a population-level, binary question: Is there credible scientific evidence that the defendant''s substance *can* cause the plaintiff''s disease in humans? If no, the case fails regardless of exposure or individual risk factors.

The evidentiary sources are well-defined. Epidemiological studies showing statistically significant elevated risk constitute the gold standard. IARC monographs classifying an agent as Group 1 provide strong regulatory support, as do EPA''s Integrated Risk Information System (IRIS) assessments and ATSDR toxicological profiles. Mechanistic data—animal toxicology studies, in vitro models, pathway analyses—supplement epidemiology, particularly for non-cancer endpoints where human epidemiology may be sparse.

However, regulatory agency classification is not dispositive of general causation; the plaintiff bears the burden of proving general causation by a preponderance of the evidence. A Group 1 IARC classification creates a rebuttable presumption of hazard, but the defendant can introduce contrary evidence to dispute causation. Similarly, the absence of an EPA RfD does not imply causation; it may simply reflect regulatory conservatism or data gaps.

In practice, general causation is most vulnerable to challenge when the epidemiological evidence is sparse, contradictory, or limited to occupational cohorts not representative of the plaintiff''s exposure window or route. If the plaintiff claims dermal absorption of a substance studied only in inhalation exposures, defendants argue the disease mechanism differs. If published epidemiology shows causation only in males and the plaintiff is female, defendants contest applicability.

The lawyer''s burden is to assemble multiple independent lines of evidence—not cherry-pick favorable studies. A toxicologist opining that substance X causes disease Y without citing the relevant epidemiological literature, negative studies, or mechanistic gaps risks Daubert exclusion as unreliable.',
'General causation is your gate-opener. If the court agrees that substance X can cause disease Y, the case survives. If not, it''s over. Build a paper trail: obtain and cite IARC, EPA IRIS, and ATSDR assessments; search PubMed for all human epidemiological studies, including null results; have your expert review and distinguish them. Anticipate the defense: they will cite negative cohort studies, argue confounding was not adequately controlled, or claim the exposure route differs fundamentally. Your expert''s report must address these head-on.',
'General causation testimony is rarely excluded outright under FRE 702 if the expert cites epidemiological literature and major regulatory agency conclusions. However, courts increasingly require the expert to quantify the strength of evidence and to explain how mechanistic data supplements (or contradicts) epidemiology. Vague opinions ("it''s possible" or "the literature supports it") fail FRE 702(c)—unreliable methodology. Specific, quantified, peer-reviewed support passes.',
'{"cases": [{"citation": "Hines v. Consolidated Rail Corp., 926 F.2d 262 (3d Cir. 1991)", "ratio": "Causation must rest on reliable epidemiological and scientific foundation; speculation insufficient"}, {"citation": "In re Rezulin (Troglitazone) Products Liability Litigation, 369 F. Supp. 2d 468 (S.D.N.Y. 2005)", "ratio": "Epidemiological evidence of association in published studies required; case report data alone unreliable for general causation"}]}',
ARRAY['causation-in-fact (first prong)', 'capable-of-causing-disease'],
ARRAY['iarc-monographs', 'iarc-group-1', 'atsdr-toxicological-profile', 'epa-iris', 'hazard-vs-risk', 'specific-causation', 'mechanism-of-action']
),

('specific-causation', 'Specific Causation', 'concept',
'Second-level causation: Did substance X cause *this plaintiff''s* disease, given this dose, exposure window, individual susceptibilities, and absence of alternative etiologies?',
'Specific causation is where toxic-tort litigation lives or dies. General causation (substance X can cause disease Y) is necessary but not sufficient; the plaintiff must prove that the defendant''s product *actually caused* the plaintiff''s disease in this case. This requires individualized evidence: exposure records, biomarker measurements, dose-response modeling, medical history, and differential diagnosis ruling out competing etiologies.

The evidentiary framework rests on three pillars. First: temporal relationship. The exposure must predate disease onset by a plausible latency window. Second: dose and route. The plaintiff''s absorbed dose must be sufficient to produce the disease using published dose-response data. Third: biological plausibility and mechanism. The plaintiff''s biomarkers must show exposure and, ideally, correlate with individual risk factors.

The Bradford Hill criteria operationalize specific causation: consistency (multiple studies show the association), dose-response (stronger exposure, higher risk), temporality (exposure before disease), biological plausibility, and coherence with known disease mechanisms. Courts weigh these factors holistically; no single criterion is dispositive.

Specific causation is vulnerable to alternative-cause defenses. If the plaintiff is a lifetime smoker with documented lung disease and no occupational asbestos exposure records, claiming asbestos caused mesothelioma becomes implausible. If the plaintiff has three competing etiologies, and the toxicologist fails to rule them out quantitatively, the opinion fails Daubert. This is where cookie-cutter expert opinions collapse: individual case facts demand individualized analysis.',
'Specific causation is your second gate. You clear general causation with regulatory agency findings and population epidemiology; you clear specific causation by proving *this plaintiff, with this exposure, in this timeframe, with this dose* suffered disease X. Demand: (1) complete exposure history; (2) biomarker data if available; (3) dose estimates tied to published literature; (4) detailed differential diagnosis addressing every competing cause; (5) expert narrative explaining why, despite alternatives, the defendant''s product is more probable than not the cause. Opposing counsel will attack dose sufficiency and alternative etiologies; your expert''s report must preempt every objection with quantified analysis.',
'Specific causation testimony fails FRE 702 most often on prong (d) "reliable application" when the expert omits differential diagnosis, assumes unexplained exposures, or extrapolates from low-dose animal studies without bridging mechanistic or biomarker evidence. Courts scrutinize whether the expert applied standard epidemiological controls for confounders. Courts now demand explicit, quantified ruling-out of alternatives.',
'{"cases": [{"citation": "Kelley v. General Motors Corp., 202 Cal.App.3d 695 (1988)", "ratio": "Specific causation requires individualized exposure and dose-response analysis; expert must address competing etiologies"}, {"citation": "In re Lipitor (Atorvastatin Calcium) Products Liability Litigation, 892 F.3d 624 (4th Cir. 2018)", "ratio": "Excluded opinion finding causation where expert failed to adequately address confounders and alternative medical causes"}]}',
ARRAY['causation-as-applied', 'individual-causation', 'proximate-cause'],
ARRAY['general-causation', 'bradford-hill-criteria', 'biomarker', 'mechanism-of-action', 'dose-response']
),

('every-exposure-doctrine', 'Every Exposure Doctrine', 'concept',
'Theory in fiber-disease litigation: each and every exposure above background contributes to cumulative disease risk. Jurisdiction-dependent; some courts reject as scientifically unsound, others admit if supported by cohort and mechanistic evidence.',
'The "every-exposure doctrine" is a causation theory most prominent in asbestos, silica, and occupational lung-disease litigation. It posits that *any* exposure to a respirable fiber above ambient background increases disease risk cumulatively; no exposure is "safe," and thus any defendant exposing the plaintiff to any amount of asbestos bears potential liability. This contrasts with threshold-based theories.

The doctrine emerged from asbestos epidemiology, particularly research showing that occupational cohorts all exhibited elevated mesothelioma risk, with no clear dose floor. Defense toxicologists counter that the epidemiological data is confounded, that animal studies show mesothelioma follows a threshold dose, and that the "every exposure" framing is biologically implausible.

State courts are split. Florida Supreme Court, in Crane Co. v. DeLisle, 258 So. 3d 1219 (Fla. 2018), upheld a jury verdict based partly on expert testimony applying the every-exposure doctrine, reversing the trial court''s Daubert exclusion. The expert, Dr. Myron Dahlgren, testified that a 10-year cumulative occupational exposure to asbestos-containing insulation was capable of causing mesothelioma even at exposure levels below OSHA regulatory thresholds. Pennsylvania, Texas, and several federal circuits have rejected the doctrine as unsupported speculation.

The strategic distinction: if your jurisdiction accepts the every-exposure doctrine and your expert can cite supportive cohort data and mechanistic plausibility, causation is easier. If your jurisdiction rejects it, the burden is higher—you must show the plaintiff''s cumulative dose exceeded published NOAEL/LOAEL estimates.',
'The every-exposure doctrine is jurisdiction-specific gold or poison. Before relying on it, research your state''s appellate posture: does the court accept cumulative-exposure causation theories absent a quantified dose-response threshold? If yes, emphasize your expert''s reliance on published occupational cohort data and mechanistic coherence. If your jurisdiction rejects the doctrine, pivot to traditional specific-causation: quantify the plaintiff''s cumulative dose, apply published NOAEL/LOAEL data, and show the plaintiff''s exposure exceeded the no-effect threshold. Crane v. DeLisle is your gold standard if the case is in Florida.',
'Every-exposure-doctrine testimony triggers intense FRE 702(c) scrutiny: Is the methodology published and peer-reviewed, or is it an ad-hoc assertion? Daubert challenges demand that the expert cite the specific epidemiological studies supporting cumulative-exposure causation, explain their sample sizes and control for confounders, and address why animal studies showing threshold doses are distinguishable. Courts increasingly exclude every-exposure opinions as speculative when the expert fails to quantify dose or distinguish the plaintiff''s exposure profile from background.',
'{"cases": [{"citation": "Crane Co. v. DeLisle, 258 So. 3d 1219 (Fla. 2018)", "ratio": "Affirmed every-exposure doctrine when expert opinion supported by occupational cohort data and mechanistic plausibility; Daubert exclusion reversed"}, {"citation": "Betz v. Pneumo Abex, LLC, 2012 PA Super 413 (Pa. Super. 2012)", "ratio": "Rejected every-exposure doctrine as scientifically unsupported; epidemiological evidence did not establish causation below regulatory thresholds"}, {"citation": "Bostic v. Georgia-Pacific Corp., 447 S.W.3d 670 (Tex. 2014)", "ratio": "Excluded every-exposure testimony; required showing dose-response or quantified causal link"}]}',
ARRAY['cumulative-exposure doctrine', 'any-exposure-contributes'],
ARRAY['specific-causation', 'dose-response', 'biomarker', 'mechanism-of-action', 'bradford-hill-criteria']
),

('biomarker', 'Biomarker', 'methodology',
'Measurable substance or metabolite in blood, urine, hair, tissue, or biological fluid indicating exposure, susceptibility, or disease effect. Example: serum dioxin, urinary glyphosate, blood lead.',
'A biomarker is a quantifiable biological indicator of exposure status, individual susceptibility, or disease process. In toxic-tort litigation, biomarkers convert abstract exposure claims into measurable evidence that resonates with juries. Common examples: urinary glyphosate (herbicide exposure), serum PCB congeners (persistent organic pollutant burden), plasma phthalate metabolites (plastic additives), tooth or bone lead (cumulative lead exposure), serum dioxin (combustion and chemical manufacturing exposure).

Three categories exist. Exposure biomarkers measure the parent compound or metabolite in biological matrices; they directly confirm exposure and, if quantified and compared to published reference ranges, establish dose estimates. Effect biomarkers reflect early disease processes: elevated alkaline phosphatase suggesting liver dysfunction, shortened telomere length indicating cellular stress. Susceptibility biomarkers identify individual genetic or acquired risk factors.

For legal causation, exposure biomarkers are strongest: they provide objective, repeatable measurements. A urinary glyphosate level of 10 ng/mL paired with published reference ranges immediately establishes the plaintiff had above-baseline exposure. Effect biomarkers are weaker because they may reflect competing etiologies. Susceptibility biomarkers are most controversial: a genetic polymorphism does not prove disease causation, only that an individual is at elevated risk if exposed.

Strategic use in litigation: (1) demand early biomarker testing (exposure biomarkers degrade over years); (2) compare to published population-reference data; (3) establish dose-response correlation (higher biomarker, steeper disease trajectory); (4) combine with mechanistic evidence. Weaknesses are specificity: does the biomarker measure *only* exposure to the defendant''s product, or could background environmental or dietary sources inflate readings? PCBs, for example, bioaccumulate from legacy contamination in fish.',
'Biomarker evidence is jury gold if properly curated. It transforms "the plaintiff may have been exposed" into "we measured 4.2 ng/mL in the plaintiff''s serum, and published industrial hygiene data shows occupational exposures to the defendant''s product reach 8-15 ng/mL." Obtain: (1) biomarker measurements from accredited labs with published quality-control protocols; (2) published reference ranges or occupational exposure studies linking biomarker levels to cumulative dose; (3) literature supporting the biomarker''s specificity; (4) data on biomarker half-life and decay, so you can estimate historical exposure if the specimen was collected years post-exposure. Opposing counsel will attack: "Background dietary sources inflate this measurement"; "The lab''s quality control is inadequate"; "No published dose-response exists between this biomarker and the plaintiff''s disease."',
'Biomarker testimony passes FRE 702 prong (c) if the biomarker has been published in peer-reviewed epidemiology and validated by multiple independent labs. Prong (d) "reliable application" is contested when the expert fails to address specificity and when biomarker levels are compared to population means without individual-level dose-response justification. Courts increasingly demand publication of the biomarker''s utility in distinguishing exposed from unexposed individuals and require the expert to explain the methodological chain from biomarker level to disease risk.',
'{"biomarkers": [{"name": "Urinary glyphosate", "route": "ingestion, dermal", "specificity": "High for agricultural/lawn exposure"}, {"name": "Serum PCB congeners", "route": "ingestion, inhalation, dermal", "specificity": "Medium; occupational exposures show distinct congener signatures"}, {"name": "Plasma phthalate metabolites", "route": "ingestion, dermal", "specificity": "Medium; ubiquitous environmental source"}, {"name": "Blood lead", "route": "ingestion, inhalation", "specificity": "High; tooth/bone lead shows cumulative burden"}]}',
ARRAY['biological marker', 'body burden', 'biological exposure index'],
ARRAY['mechanism-of-action', 'dose-response', 'hazard-vs-risk', 'general-causation', 'specific-causation']
),

('mechanism-of-action', 'Mechanism of Action', 'methodology',
'Molecular/cellular pathway by which a substance produces biological effect. Examples: PCB-AhR agonism; glyphosate shikimate-pathway inhibition; asbestos ROS + inflammation.',
'Mechanism of action (MOA) is the biological pathway through which a toxicant produces disease. Understanding MOA strengthens causation by establishing "biological plausibility"—answering the question: "How *does* this substance harm this person?" in mechanistic detail, not just statistical association.

Classic examples: (1) PCBs as aryl hydrocarbon receptor (AhR) agonists, activating transcription of cytochrome P450 enzymes and causing enzyme induction, metabolic stress, and cellular proliferation; (2) glyphosate''s inhibition of the shikimate pathway in plants, and putative disruption of mammalian microbial gut metabolism and estrogen signaling; (3) asbestos as chronic generator of reactive oxygen species (ROS), leading to oxidative DNA damage, chromosomal translocations, and multi-hit carcinogenesis; (4) lead''s inhibition of ALAD in heme synthesis, accumulation of delta-ALA, and neurological effects.

In litigation, mechanistic evidence serves two purposes. First, it bridges population-level epidemiology to individual causation: if the mechanism is well-characterized and the plaintiff''s biomarkers show evidence of the mechanism at work, the causal chain becomes tangible. Second, it buttresses general causation: if no human epidemiology exists but animal studies, in vitro models, and pathway analyses all converge on a single mechanism, courts may accept mechanistic reasoning as sufficient for plausibility.

Mechanistic evidence is not a substitute for epidemiology; the strongest toxic-tort cases combine epidemiological association with mechanistic coherence. However, for rare diseases or newly recognized exposures, mechanistic data may be all that exists. Conversely, weak mechanisms (e.g., "the chemical *could* disrupt hormones, but no known estrogen-receptor binding") weaken causation if epidemiology is sparse.',
'Mechanism testimony is your narrative glue: it explains to the jury *why* this substance caused disease *in this person*. Obtain: (1) peer-reviewed papers on the MOA (PubMed search, cite DOI); (2) data showing the plaintiff''s dose is sufficient to activate the pathway (compare to in vitro EC50 or animal NOAEL); (3) biomarker or medical evidence that the mechanism is active in the plaintiff; (4) expert testimony that the mechanism is biologically plausible and supported by the field. Opposing counsel will attack the mechanism as "speculative," "not proven in humans," or "theoretical." Pre-empt by citing published mechanism papers, animal dose-response studies, and mechanistic consistency with the plaintiff''s clinical presentation.',
'Mechanism-of-action testimony is admissible under FRE 702 if the expert cites published research on the pathway, explains how the pathway operates at the molecular level, and connects the pathway to the plaintiff''s disease outcome and biomarker data. Courts are skeptical of purely theoretical mechanisms lacking in vivo validation or human evidence. The Daubert question for MOA is usually prong (c) "reliable principles and methods": is the mechanism based on peer-reviewed biology or extrapolation from a single animal study? Courts increasingly demand that the expert explain where the mechanism was first described, how it has been validated, and what alternative mechanisms might produce the same disease.',
'{"mechanisms": [{"substance": "PCB congeners", "pathway": "Aryl hydrocarbon receptor (AhR) agonism"}, {"substance": "Glyphosate", "pathway": "Inhibition of 5-enolpyruvylshikimate-3-phosphate (EPSPS) synthase"}, {"substance": "Asbestos fibers", "pathway": "Chronic inflammation and ROS production"}, {"substance": "Lead (Pb)", "pathway": "Inhibition of ALAD and sulfhydryl-containing enzymes"}]}',
ARRAY['pathophysiology', 'biological pathway', 'causal mechanism'],
ARRAY['biomarker', 'dose-response', 'hazard-vs-risk', 'general-causation', 'specific-causation', 'bradford-hill-criteria']
),

('dose-response', 'Dose-Response Relationship', 'methodology',
'Quantitative relationship between magnitude of exposure and probability/severity of effect. Linear, threshold, and hormetic curves. Key to determining if plaintiff''s dose was sufficient to cause harm.',
'Dose-response is the fundamental principle of toxicology: the probability and severity of a biological effect increase with increasing exposure. The dose-response curve describes this relationship, and its shape—linear, sigmoidal (threshold), biphasic (hormetic)—determines whether regulatory and legal conclusions about safe exposure levels are justified.

Three canonical models exist. Linear-no-threshold (LNT) assumes risk increases proportionally to dose with no safe threshold; it is the default regulatory assumption for genotoxic carcinogens and is conservative. Threshold models posit a no-observed-adverse-effect level (NOAEL) below which no effect occurs; this is the basis for derivation of EPA''s Reference Dose (RfD) and ATSDR''s Minimal Risk Level (MRL). Hormetic models claim low doses confer protective or beneficial effects despite high-dose toxicity; this is controversial and rarely accepted in regulatory frameworks.

In litigation, the dose-response curve is where causation lives or dies. If published epidemiology or animal studies define a dose-response curve, and the plaintiff''s biomarker or exposure estimates place them *above* the curve''s threshold or inflection point, specific causation is supported. Conversely, if the plaintiff''s dose is far below published NOAEL/LOAEL values, the defense argues no plausible causation.

The expert''s burden is to (1) identify published dose-response data for the substance and disease at issue; (2) estimate the plaintiff''s cumulative dose using occupational hygiene monitoring, biomarker decay-back calculations, or job-exposure matrices; (3) compare the plaintiff''s dose to the curve''s critical points (NOAEL, LOAEL); (4) explain why, despite dose estimates, causation remains plausible. Disagreement over dose estimation is the most frequent battleground: the plaintiff''s expert estimates high exposure based on worst-case job duties; the defense calculates conservative exposure based on limited occupational samples.',
'Dose-response is the leverage point in litigation. If you can show the plaintiff''s cumulative dose exceeded published NOAEL/LOAEL, the case is stronger. Obtain: (1) published dose-response curves for the substance and disease (animal studies, occupational cohorts); (2) detailed exposure history: job titles, tasks, duration, frequency, use of PPE; (3) biomarker data if available, tied to dose-response studies; (4) expert narrative explaining the dose reconstruction methodology and its assumptions. Opposing counsel will attack dose estimates as "inflated," "based on worst-case assumptions," or "inconsistent with OSHA exposure data." Your expert must defend the dose calculation with published occupational hygiene methodology.',
'Dose-response testimony is admissible under FRE 702(c) if the expert cites published dose-response data and applies it logically to the plaintiff. Prong (d) "reliable application" is contested when dose estimates are speculative or when the expert assumes exposures without published foundation. Courts scrutinize whether dose estimates use published occupational exposure data or ad-hoc guesses. Recent cases exclude dose-response testimony when the expert extrapolates linearly from high-dose animal studies to low-dose human exposures without explaining the biological or pharmacokinetic basis for the extrapolation.',
'{"dose_response_models": [{"model": "Linear-no-threshold (LNT)", "shape": "Linear through origin", "regulatory_use": "Default for genotoxic carcinogens"}, {"model": "Sigmoidal (threshold)", "shape": "S-shaped curve with inflection point (NOAEL)", "regulatory_use": "Non-cancer endpoints, non-genotoxic substances"}, {"model": "Hormetic (biphasic)", "shape": "Low-dose stimulation, high-dose inhibition", "regulatory_use": "Rare; controversial"}]}',
ARRAY['exposure-response relationship', 'dose-effect curve', 'concentration-response'],
ARRAY['noael-loael', 'mechanism-of-action', 'biomarker', 'hazard-vs-risk', 'bradford-hill-criteria', 'specific-causation']
),

('reference-dose', 'Reference Dose (RfD)', 'metric',
'EPA-derived daily exposure level estimated to be without appreciable lifetime risk of adverse effects. Calculated as NOAEL or LOAEL divided by uncertainty factors (typically 100×). Conservative by design.',
'The Reference Dose (RfD) is a quantitative risk assessment metric developed by the U.S. EPA to define a presumptively "safe" daily exposure. It is derived from animal toxicology or human epidemiological data, typically calculated as RfD = NOAEL / UF, where UF (uncertainty factor) is a composite of safety margins. Standard UF is 100× (10× for interspecies extrapolation from animal to human; 10× for intraspecies variability accounting for sensitive subpopulations). The RfD is conservative: it assumes lifetime daily exposure at this level carries no appreciable additional risk above background disease incidence.

EPA publishes RfDs in the IRIS database (Integrated Risk Information System). ATSDR publishes parallel metrics called Minimal Risk Levels (MRLs) for acute, intermediate, and chronic exposures. For carcinogens, the EPA does not derive an RfD; instead, it assigns a cancer slope factor allowing linear-no-threshold risk calculation.

In litigation, the RfD serves as an anchor for the "ordinary safe exposure" narrative but is *not* a bright line. Exceeding the RfD does not prove harm; falling below it does not prove safety. Why? The RfD is constructed conservatively: (1) it assumes lifetime daily exposure; (2) it applies to the *average* human; (3) it is often derived from sparse animal data with large uncertainty factors. Conversely, the RfD is not a liability threshold: exposure at 0.99× RfD is not "safe" and exposure at 1.01× RfD is not automatically "toxic."

In practice, lawyers use the RfD as a contextual reference: "This plaintiff''s estimated daily exposure was 2× the EPA RfD, suggesting exposure in the range where toxicological effects were observed in animal studies," or "The plaintiff''s exposure was <0.5× RfD, placing it in a range below the no-effect threshold." This is calibration, not causation proof. Courts have held that RfD exceedance, without additional causation evidence (dose-response, biomarker, mechanism), is insufficient for expert opinion of specific causation.',
'The RfD is your toxicology ruler: it allows the expert (and jury) to visualize where the plaintiff''s dose sits on the toxicological landscape. Obtain: (1) the EPA IRIS RfD (or ATSDR MRL) for the substance of interest; (2) the derivation: which animal study was used, what was the NOAEL, what were the uncertainty factors; (3) your plaintiff''s estimated daily exposure; (4) expert narrative: "The RfD is 0.001 mg/kg/day, derived from a 2-year rat study with NOAEL of 0.1 mg/kg/day. This plaintiff''s estimated exposure was 0.005 mg/kg/day, approximately 5× the RfD. This places the plaintiff in an exposure range where animal studies observed [specific effect]." Avoid stating "RfD exceedance = harm"; instead, frame it as "exposure in a range of toxicological concern."',
'RfD testimony is usually admissible under FRE 702 as expert explanation of regulatory toxicology. However, courts are alert to misuse: if the expert claims RfD exceedance *per se* causes disease (prong d "reliable application" failure), the opinion is excluded. Courts have held that RfD or reference values are useful context but do not substitute for mechanistic or epidemiological causation evidence. The strongest RfD testimony cites the EPA derivation, explains the underlying NOAEL and uncertainty factors, and uses RfD as a benchmark without claiming RfD is a liability threshold.',
'{"references": [{"name": "EPA IRIS (Integrated Risk Information System) Database", "url": "https://www.epa.gov/iris"}, {"name": "ATSDR Toxicological Profiles and MRL Derivations", "url": "https://www.atsdr.cdc.gov/toxprofiles/index.asp"}]}',
ARRAY['RfD', 'reference dose', 'acceptable daily intake'],
ARRAY['noael-loael', 'dose-response', 'hazard-vs-risk', 'epa-iris', 'atsdr-toxicological-profile']
)

ON CONFLICT (slug) DO NOTHING;
